# Dependencias
FROM node:21-alpine3.19 as deps
WORKDIR /usr/src/app
COPY package*.json ./
RUN npm ci

# Build
FROM node:21-alpine3.19 as build
WORKDIR /usr/src/app
COPY --from=deps /usr/src/app/node_modules ./node_modules
COPY . .
RUN npx prisma generate
RUN npm run build

# Producción
FROM node:21-alpine3.19 as prod
WORKDIR /usr/src/app
ENV NODE_ENV=production

COPY --from=build /usr/src/app/node_modules ./node_modules
COPY --from=build /usr/src/app/dist ./dist
COPY --from=build /usr/src/app/prisma ./prisma

RUN npx prisma generate

USER node
EXPOSE 3000
CMD ["node", "dist/main"]